version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu
