spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: ${SPRING_PROFILES_ACTIVE}
  flyway:
    placeholder-replacement: false

management:
  endpoints:
    web:
      exposure:
        include: health

mail:
  token:
    verify-base-url: ${MAIL_TOKEN_VERIFY_BASE_URL:http://localhost:8080/api/v1/mails/verify}
    verify-success-url: ${MAIL_TOKEN_VERIFY_SUCCESS_URL:http://localhost:8080/mail/verify-success.html}
    verify-failure-url: ${MAIL_TOKEN_VERIFY_FAILURE_URL:http://localhost:8080/mail/verify-failure.html}
