spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  jwt:
    issuer: ${JWT_ISSUER}
    access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS}
    refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME}
    refresh-cookie-path: ${JWT_REFRESH_COOKIE_PATH}
    refresh-cookie-same-site: ${JWT_REFRESH_COOKIE_SAME_SITE}
    refresh-cookie-secure: ${JWT_REFRESH_COOKIE_SECURE:true}
    secret: ${JWT_SECRET}

challenge:
  otp-length: ${OTP_LENGTH}
  otp-ttl-seconds: ${OTP_TTL_SECONDS}
  otp-max-attempts: ${OTP_MAX_ATTEMPTS}
  cooldown-seconds: ${OTP_REQUEST_COOLDOWN}
  confirmation-token-ttl-seconds: ${CONFIRMATION_TOKEN_TTL_SECONDS}

mail:
  token:
    verify-base-url: ${MAIL_TOKEN_VERIFY_BASE_URL}
    verify-success-url: ${MAIL_TOKEN_VERIFY_SUCCESS_URL}
    verify-failure-url: ${MAIL_TOKEN_VERIFY_FAILURE_URL}

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4.1-mini
